configs:
  cm:
    application.resourceTrackingMethod: annotation
    timeout.reconciliation: 60s
  params:
    "server.insecure": true
server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - argocd.127.0.0.1.nip.io
  extraArgs:
    - --insecure


